"""Use keys

Revision ID: 7f8cf24a694c
Revises: a5b36ed0e02e
Create Date: 2023-10-21 20:13:51.112934

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8cf24a694c"
down_revision: Union[str, None] = "a5b36ed0e02e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("UsersBadges", sa.Column("blob_id", sa.LargeBinary(), nullable=False))
    op.drop_constraint("UsersBadges_blob_key", "UsersBadges", type_="unique")
    op.create_foreign_key(None, "UsersBadges", "Badges", ["blob_id"], ["id"])
    op.drop_column("UsersBadges", "blob")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UsersBadges",
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "UsersBadges", type_="foreignkey")
    op.create_unique_constraint("UsersBadges_blob_key", "UsersBadges", ["blob"])
    op.drop_column("UsersBadges", "blob_id")
    # ### end Alembic commands ###
