"""Update tables

Revision ID: ad16d6501998
Revises: f75f245352ee
Create Date: 2023-10-21 20:54:43.975381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad16d6501998"
down_revision: Union[str, None] = "f75f245352ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Badges", sa.Column("description", sa.String(length=150), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Badges", "description")
    # ### end Alembic commands ###
