"""UsersBadges

Revision ID: af20387d014c
Revises: 7f8cf24a694c
Create Date: 2023-10-21 20:18:01.528416

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af20387d014c"
down_revision: Union[str, None] = "7f8cf24a694c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob"),
    )
    op.create_table(
        "UsersBadges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blob_id", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["Badges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UsersBadges")
    op.drop_table("Badges")
    # ### end Alembic commands ###
