"""Bytes to path

Revision ID: 5204624ec423
Revises: 6eb66c0b5e4d
Create Date: 2023-10-21 21:18:40.011534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5204624ec423'
down_revision: Union[str, None] = '6eb66c0b5e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Badges', sa.Column('path', sa.String(length=150), nullable=False))
    op.drop_constraint('Badges_blob_key', 'Badges', type_='unique')
    op.drop_column('Badges', 'blob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Badges', sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.create_unique_constraint('Badges_blob_key', 'Badges', ['blob'])
    op.drop_column('Badges', 'path')
    # ### end Alembic commands ###
