"""More bytes lets gooo

Revision ID: 4ceff3f22a11
Revises: ad16d6501998
Create Date: 2023-10-21 21:08:51.356642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ceff3f22a11'
down_revision: Union[str, None] = 'ad16d6501998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Model',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Model_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Model_pkey'),
    sa.UniqueConstraint('blob', name='Model_blob_key')
    )
    # ### end Alembic commands ###
