"""Differ for users and all badges

Revision ID: a5b36ed0e02e
Revises: 1ddbbb43c69b
Create Date: 2023-10-21 20:04:21.959508

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b36ed0e02e"
down_revision: Union[str, None] = "1ddbbb43c69b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UsersBadges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob"),
    )
    op.drop_constraint("Badges_user_id_fkey", "Badges", type_="foreignkey")
    op.drop_column("Badges", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Badges",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key("Badges_user_id_fkey", "Badges", "User", ["user_id"], ["id"])
    op.drop_table("UsersBadges")
    # ### end Alembic commands ###
