"""Create Badges

Revision ID: f106fd470d8b
Revises: 4145e249c83c
Create Date: 2023-10-21 19:45:46.925125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f106fd470d8b'
down_revision: Union[str, None] = '4145e249c83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Badges')
    # ### end Alembic commands ###
