"""Add uniqueness

Revision ID: b91f5a2abba6
Revises: 5b869c42fe65
Create Date: 2023-10-21 13:29:45.252045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91f5a2abba6'
down_revision: Union[str, None] = '5b869c42fe65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Photo', ['blob'])
    op.create_unique_constraint(None, 'Plant', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Plant', type_='unique')
    op.drop_constraint(None, 'Photo', type_='unique')
    # ### end Alembic commands ###
