"""Model Badges

Revision ID: 1ddbbb43c69b
Revises: f106fd470d8b
Create Date: 2023-10-21 19:52:29.445139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddbbb43c69b'
down_revision: Union[str, None] = 'f106fd470d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Model')
    # ### end Alembic commands ###
